### ISSUE TITLE
Markdown should be parsed entirely for preview

### ISSUE THREAD

**Issue by burgerdev** [meddle0x53/blogit#1]
Hi Meddle,

first of all, thanks for blogit - after I discovered it I *just knew* it was the right tool for me! To the problem at hand:

Consider the following markdown:

```md
# Title

[Lorem ipsum][1] dolor sit amet, 
consectetuer adipiscing elit.

[1]: https://loremipsumgenerator.com/
```

If I set `max_lines_in_preview` to 3, I would still expect the link to be resolved. Since [the pipeline generating preview](https://github.com/meddle0x53/blogit/blob/fb7883d64f684b3f04e6f73e7554f29a1faea23e/lib/blogit/models/post/meta.ex#L110) does split first and parse markdown only of head, the link at the bottom is lost and the html generated is just

```html
<!-- css and other distractions omitted -->
<h2>Title</h2>
<p>[Lorem ipsum][1] dolor sit amet, </p>
<a><h4>[...]</h4></a>
<hr class="post-divider" />
```

instead of 

```html
<!-- css and other distractions omitted -->
<h2>Title</h2>
<p><a href="https://loremipsumgenerator.com/">Lorem ipsum</a>dolor sit amet, </p>
<a><h4>[...]</h4></a>
<hr class="post-divider" />
```

Cheers, Markus

**Comment by meddle0x53** [comment]
To be honest I've never used reference links in  markdown. And that's a miss!
Of course we should support them in the preview, nice find and nicely described issue.
Will try to resolve it as soon as possible.

**Comment by meddle0x53** [comment]
It now has a PR. I'll be merging it and releasing `1.1.1` tomorrow, test it if you want before that.
